#!/bin/bash


file_list=$(find . -maxdepth 1 -not -type d)

for file in $file_list
do
  filename=$(echo $file | sed 's/\.\///g')
  filetype=$(file --mime-type -b $file)

  if [[ $filetype =~ image* ]] 
  then
    new_filename="$(md5sum $file | awk '{ print $1 }').${file##*.}"

    if [[ $filename != $new_filename ]]
    then
      echo "renaming ${filename} to ${new_filename}"
      mv $file $new_filename
    fi
  fi
done

